# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_knn_c_euclidean <- function(X, X0, y) {
    .Call(`_myknn_my_knn_c_euclidean`, X, X0, y)
}

my_knn_c_minkowsky <- function(X, X0, y, p) {
    .Call(`_myknn_my_knn_c_minkowsky`, X, X0, y, p)
}

my_knn_tuningp <- function(X, X0, y, possible_p) {
    .Call(`_myknn_my_knn_tuningp`, X, X0, y, possible_p)
}

rcpp_hello_world <- function() {
    .Call(`_myknn_rcpp_hello_world`)
}

